# Generated by Django 4.2.8 on 2023-12-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data inici')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data final')),
            ],
            options={
                'verbose_name': "Grup d'autors",
                'verbose_name_plural': "Grups d'autors",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Tag de contacte',
                'verbose_name_plural': 'Tags de contactes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('surnames', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cognoms')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telèfon')),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telèfon 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 2')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentaris')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('tags', models.ManyToManyField(blank=True, to='people.contacttag', verbose_name='Etiquetes')),
            ],
            options={
                'verbose_name': 'Contacte',
                'verbose_name_plural': 'Contactes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('surnames', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cognoms')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data naixement')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Data defunció')),
                ('groups', models.ManyToManyField(blank=True, to='people.authorgroup', verbose_name='Grups')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autors',
                'ordering': ['name'],
            },
        ),
    ]
