# Generated by Django 4.2.8 on 2023-12-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(null=True, verbose_name='Descripció')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data inici')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data final')),
            ],
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('surnames', models.CharField(max_length=100, null=True, verbose_name='Cognoms')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Telèfon')),
                ('phone_2', models.CharField(max_length=15, null=True, verbose_name='Telèfon 2')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('email_2', models.EmailField(max_length=254, null=True, verbose_name='Email 2')),
                ('comments', models.TextField(null=True, verbose_name='Comentaris')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('tags', models.ManyToManyField(to='people.contacttag', verbose_name='Etiquetes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('surnames', models.CharField(max_length=100, null=True, verbose_name='Cognoms')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data naixement')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Data defunció')),
                ('groups', models.ManyToManyField(to='people.authorgroup', verbose_name='Grups')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
