# Generated by Django 4.2.8 on 2023-12-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripció')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Dia i hora de consulta')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Data de consulta',
                'verbose_name_plural': 'Dates de consulta',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Títol')),
                ('url', models.URLField(max_length=256, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Imatge',
                'verbose_name_plural': 'Imatges',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripció')),
            ],
            options={
                'verbose_name': 'Paraula clau',
                'verbose_name_plural': 'Paraules clau',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripció')),
            ],
            options={
                'verbose_name': 'Ubicació',
                'verbose_name_plural': 'Ubicacions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripció')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DirectSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Títol')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('works_nature', models.CharField(blank=True, choices=[('o', 'Original'), ('rf', 'Reproducció fotogràfica'), ('cp', 'Copia')], max_length=3, null=True, verbose_name="Naturalesa de l'obra")),
                ('origin', models.CharField(blank=True, max_length=150, null=True, verbose_name='Origen')),
                ('thematic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Temàtica')),
                ('critical_component', models.BooleanField(blank=True, null=True, verbose_name='Component crític')),
                ('message_lecture', models.TextField(blank=True, null=True, verbose_name='Lectura del missatge')),
                ('authors', models.ManyToManyField(blank=True, to='people.directsourceauthor', verbose_name='Autors')),
                ('aux_photos', models.ManyToManyField(blank=True, related_name='aux_photos_directsource', to='items.image', verbose_name='Imatges auxiliars')),
                ('categories', models.ManyToManyField(blank=True, to='items.category', verbose_name='Categories')),
                ('collective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.collective', verbose_name='Col·lectiu')),
                ('consultation_dates', models.ManyToManyField(blank=True, to='items.consultationdate', verbose_name='Dates de consulta')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.location', verbose_name='Ubicació')),
                ('main_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_photo_directsource', to='items.image', verbose_name='Imatge principal')),
            ],
            options={
                'verbose_name': 'Font directa',
                'verbose_name_plural': 'Fonts directes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BibliographicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Títol')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('authors', models.ManyToManyField(blank=True, to='people.bibliographicresourceauthor', verbose_name='Autors')),
                ('categories', models.ManyToManyField(blank=True, to='items.category', verbose_name='Categories')),
                ('direct_sources', models.ManyToManyField(blank=True, to='items.directsource', verbose_name='Fonts directes')),
                ('key_words', models.ManyToManyField(blank=True, to='items.keyword', verbose_name='Paraules clau')),
            ],
            options={
                'verbose_name': 'Recurs bibliogràfic',
                'verbose_name_plural': 'Recursos bibliogràfics',
                'ordering': ['title'],
            },
        ),
    ]
