# Generated by Django 4.2.8 on 2023-12-16 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Descripció')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Descripció')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Descripció')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Títol')),
                ('dimensions', models.TextField(blank=True, null=True, verbose_name='Dimensions')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('origin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Origen')),
                ('authors', models.ManyToManyField(to='people.author', verbose_name='Autor')),
                ('categories', models.ManyToManyField(to='items.category', verbose_name='Categories')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.authorgroup', verbose_name='Grup')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.location', verbose_name='Ubicació')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.material', verbose_name='Materials')),
            ],
        ),
    ]
