WELCOME_MESSAGE_INTRO = [
    "Hola",
    "Bones",
    "Benvolguda",
    "Hola de nou",
    "Heeeeeeeyyy",
    "Hola gominola",
    "Hola estimada",
    "Bon dia carinyosa",
    "Com estàs dolça",
    "Què tal estimada",
    "Què hi ha de nou bella",
    "Com te trobes --- dels meus somnis",
    "Què tal estàs --- joia del meu cor",
    "Com va el teu dia ---  tendra",
    "Què tal el dia ---, del meu somni",
    "Com estàs avui ---, llum del meu ser",
    "Hola --- estimada ",
    "Com estàs dolça",
    "Què passa estimada",
    "Com te va, estimada",
    "Hola pepsicola",
]

WELCOME_MESSAGE_CUQI = [
    "Cuqi",
    "Guanchale",
    "Cosker",
    "Guanche",
    "Grunch",
    "Muesli",
    "Orangutangui",
    "Crusker",
    "Cromañunker",
    "Kuasker",
    "Broncaner",
    "Coquë",
    "Monchi",
    "Caganunger",
    "Xus",
    "Salchichona",
    "Crusker dusker",
    "Cuqi formatgi",
    "Aguacatunger",
    "Carabasseta",
    "Musker",
    "Gochuchan",
    "Choricito criollo",
    "Gorgonsola",
    "Miss cirereta",
    "Miss tarta de fresa",
]

WELCOME_MESSAGE_BODY = [
    "Molts ànims amb la teva sessió d'investigació d'avui, ets sa millor.",
    "Que tinguis tota la força per a la sessió d'investigació d'avui, ets excepcional.",
    "Estic segur que ho faràs genial en la teva investigació d'avui, ets sa millor.",
    "Que tinguis molta sort amb la sessió d'investigació d'avui, ets insuperable.",
    "Molta energia per a la teva investigació d'avui, ets inigualable.",
    "Molts ànims amb la teva feina d'avui, ets la més llesteta.",
    "Tot s'amor en tu per a la sessió d'investigació d'avui, ets meravellosa.",
    "Que tot te vagi perfecte en la investigació d'avui, ets insubstituïble.",
    "Molta sort en la sessió d'investigació d'avui, ets excepcional.",
    "Molts ànims amb la teva tasca d'avui, ets sa millor.",
    "Que tinguis molt d'èxit en la teva investigació d'avui, ets insuperable.",
    "Molta força per a la sessió d'investigació d'avui, ets inigualable.",
    "Estic segur que t'anira super bé en la investigació d'avui, ets sa millor.",
    "Molts ànims amb la teva feina d'avui, ets excepcional.",
    "Tota la confiança en tu per a la investigació d'avui, ets insubstituïble.",
    "Que tot te vagi de meravella en la sessió d'investigació d'avui, ets meravellosa.",
    "Molta sort en la teva tasca d'avui, ets insuperable.",
    "Que tinguis molta energia per a la sessió d'investigació d'avui, ets sa millor.",
    "Molts ànims amb la teva investigació d'avui, ets la més llesteta.",
    "Que tot te surti genial en la investigació d'avui, ets insubstituïble.",
    "Molta força per a la teva feina d'avui, ets excepcional.",
    "Estic segur que t'anira super bé en la sessió d'investigació d'avui, ets meravellosa.",
    "Molts ànims amb la teva tasca d'avui, ets insuperable.",
    "Que tinguis tot el suport necessari per a la investigació d'avui, ets sa millor.",
    "Molta sort amb la sessió d'investigació d'avui, ets inigualable.",
    "Que tot te vagi de meravella en la teva feina d'avui, ets la més llesteta.",
    "Molta confiança en tu per a la teva tasca d'avui, ets insubstituïble.",
    "Molts ànims amb la teva investigació d'avui, ets excepcional.",
    "Que tinguis molta energia per a la sessió d'investigació d'avui, ets sa millor.",
    "Molta força per a la teva feina d'avui, ets la més llesteta.",
]
